//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codeTongCucThienTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucNguonVon
    {
        public int danhMucNguonVonId { get; set; }
        public string danhMucNguonVonName { get; set; }
        public bool isTrash { get; set; }
        public Nullable<int> danhMucCha { get; set; }
        public Nullable<int> capDanhMuc { get; set; }
    }
}
