//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codeTongCucThienTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaiNgan
    {
        public int giaiNganId { get; set; }
        public int nhiemVuId { get; set; }
        public string nhiemVuName { get; set; }
        public Nullable<decimal> giaTriThanhToan { get; set; }
        public System.DateTime thoiGianThanhToan { get; set; }
        public double tiLeGiaiNgan { get; set; }
    }
}
