//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codeTongCucThienTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoiThau
    {
        public int goiThauId { get; set; }
        public string nhaThauName { get; set; }
        public decimal giaThau { get; set; }
        public int nhiemVuId { get; set; }
    }
}
