//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codeTongCucThienTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhiemVu
    {
        public int nhiemVuId { get; set; }
        public string nhiemVuName { get; set; }
        public int danhMucId { get; set; }
        public int namKeHoach { get; set; }
        public decimal giaTriDeXuat { get; set; }
        public Nullable<decimal> giaTriGiao { get; set; }
        public int donViDeXuatId { get; set; }
        public string donViDeXuatName { get; set; }
        public int donViDuToanId { get; set; }
        public string donViDutoanName { get; set; }
        public string nguonVonName { get; set; }
        public string ghiChu { get; set; }
        public System.DateTime createTime { get; set; }
        public bool isTrash { get; set; }
        public int trangThai { get; set; }
        public Nullable<decimal> giaTriDuyet { get; set; }
        public Nullable<decimal> giaTriTrungThau { get; set; }
        public string nhaThauTrung { get; set; }
        public Nullable<decimal> giaTriQuyetToan { get; set; }
        public string userCreate { get; set; }
        public string userUpdate { get; set; }
        public System.DateTime updateTime { get; set; }
        public Nullable<decimal> giaTriHopDong { get; set; }
        public Nullable<decimal> giaTriThanhToan { get; set; }
        public decimal giaTriDeXuat2 { get; set; }
        public Nullable<System.DateTime> hanTrinh { get; set; }
    }
}
