//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codeTongCucThienTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        public int taiLieuId { get; set; }
        public string taiLieuName { get; set; }
        public string taiLieuLink { get; set; }
        public bool isTrash { get; set; }
    }
}
