//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codeTongCucThienTai.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TongCucThienTaiEntities : DbContext
    {
        public TongCucThienTaiEntities()
            : base("name=TongCucThienTaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DanhMucDonVi> DanhMucDonVis { get; set; }
        public virtual DbSet<DanhMucNguonVon> DanhMucNguonVons { get; set; }
        public virtual DbSet<DanhMucNhiemVu> DanhMucNhiemVus { get; set; }
        public virtual DbSet<GiaiNgan> GiaiNgans { get; set; }
        public virtual DbSet<LogTrangThai> LogTrangThais { get; set; }
        public virtual DbSet<NguonVonNhiemVu> NguonVonNhiemVus { get; set; }
        public virtual DbSet<NhiemVu> NhiemVus { get; set; }
        public virtual DbSet<NhiemVuTaiLieu> NhiemVuTaiLieux { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TaiLieu> TaiLieux { get; set; }
        public virtual DbSet<GoiThau> GoiThaus { get; set; }
    }
}
